# Base image
FROM node:14-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy the rest of the project files
COPY . .

# Expose a port if required
EXPOSE 3000

# Start the application
CMD [ "npm", "run", "dev" ]
